import type { NextPage } from "next";
import Head from "next/head";
import { AppShell, Navbar, Header } from "@mantine/core";
import { Prism } from "@mantine/prism";
import { Link } from "../components/Link";
import { Code } from "@mantine/core";

const demoCode = `import { Button } from '@mantine/core';

function Demo() {
  return <Button>Hello</Button>
}`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Not Backend Interview Guide | Actually for Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        padding="md"
        navbar={
          <Navbar width={{ base: 300 }} height={500} padding="xs">
            <Link href="/coding">Coding</Link>
            <Link href="/css">CSS</Link>
            <Link href="/system-design">System Design</Link>
          </Navbar>
        }
        header={
          <Header height={60} padding="xs">
            <Code>!backendInterviewGuide === frontendInterviewGuide</Code>
          </Header>
        }
      >
        <main>
          <h1>Not Backend Interview Guide | Actually for Frontend</h1>
          <Prism language="tsx">{demoCode}</Prism>
        </main>
      </AppShell>
    </div>
  );
};

export default Home;
